<?php

namespace Database\Seeders;

use App\Models\Enrolment;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EnrolmentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all learners and courses to map names to IDs
        $learners = DB::table('learners')->get()->mapWithKeys(function ($learner) {
            return [$learner->firstname . ' ' . $learner->lastname => $learner->id];
        })->toArray();

        $courses = DB::table('courses')->get()->mapWithKeys(function ($course) {
            return [$course->name => $course->id];
        })->toArray();

        $enrolments = [
            ['learner' => 'Amahle Ndlovu', 'course' => 'Computer Applications Technology', 'progress' => 45],
            ['learner' => 'Amahle Ndlovu', 'course' => 'IsiXhosa', 'progress' => 26],
            ['learner' => 'Amahle Ndlovu', 'course' => 'IsiZulu', 'progress' => 13],
            ['learner' => 'Amahle Ndlovu', 'course' => 'Life Orientation', 'progress' => 79],
            ['learner' => 'Amahle Ndlovu', 'course' => 'Physical Sciences', 'progress' => 63],
            ['learner' => 'Amahle Ndlovu', 'course' => 'Visual Arts', 'progress' => 78],
            ['learner' => 'Angel Mkhize', 'course' => 'Hospitality Studies', 'progress' => 62],
            ['learner' => 'Angel Mkhize', 'course' => 'Life Sciences', 'progress' => 55],
            ['learner' => 'Angel Mkhize', 'course' => 'Siswati', 'progress' => 34],
            ['learner' => 'Angel Mkhize', 'course' => 'Tshivenda', 'progress' => 74],
            ['learner' => 'Angel Mkhize', 'course' => 'Visual Arts', 'progress' => 3],
            ['learner' => 'Angel Stevens', 'course' => 'Electrical Technology', 'progress' => 16],
            ['learner' => 'Angel Stevens', 'course' => 'IsiZulu', 'progress' => 13],
            ['learner' => 'Angel Stevens', 'course' => 'Life Orientation', 'progress' => 67],
            ['learner' => 'Angel Stevens', 'course' => 'Life Sciences', 'progress' => 55],
            ['learner' => 'Angel Stevens', 'course' => 'Mathematics', 'progress' => 25],
            ['learner' => 'Angel Stevens', 'course' => 'Sepedi', 'progress' => 72],
            ['learner' => 'Angel Stevens', 'course' => 'Tourism', 'progress' => 19],
            ['learner' => 'Angel Stevens', 'course' => 'Visual Arts', 'progress' => 34],
            ['learner' => 'Asemahle Du Toit', 'course' => 'Dramatic Arts', 'progress' => 81],
            ['learner' => 'Asemahle Du Toit', 'course' => 'Economics', 'progress' => 86],
            ['learner' => 'Asemahle Du Toit', 'course' => 'Music', 'progress' => 16],
            ['learner' => 'Asemahle Du Toit', 'course' => 'Physical Sciences', 'progress' => 18],
            ['learner' => 'Asemahle Du Toit', 'course' => 'Siswati', 'progress' => 5],
            ['learner' => 'Asemahle Du Toit', 'course' => 'Xitsonga', 'progress' => 22],
            ['learner' => 'Asemahle Mkhize', 'course' => 'Economics', 'progress' => 81],
            ['learner' => 'Asemahle Mkhize', 'course' => 'Information Technology', 'progress' => 50],
            ['learner' => 'Asemahle Mkhize', 'course' => 'IsiNdebele', 'progress' => 24],
            ['learner' => 'Asemahle Mkhize', 'course' => 'IsiXhosa', 'progress' => 71],
            ['learner' => 'Asemahle Mkhize', 'course' => 'Sepedi', 'progress' => 71],
            ['learner' => 'Asemahle Mkhize', 'course' => 'Tshivenda', 'progress' => 62],
            ['learner' => 'Asemahle Nkosi', 'course' => 'Economics', 'progress' => 70],
            ['learner' => 'Asemahle Nkosi', 'course' => 'Geography', 'progress' => 61],
            ['learner' => 'Asemahle Nkosi', 'course' => 'IsiNdebele', 'progress' => 87],
            ['learner' => 'Asemahle Nkosi', 'course' => 'IsiZulu', 'progress' => 63],
            ['learner' => 'Asemahle Nkosi', 'course' => 'Siswati', 'progress' => 75],
            ['learner' => 'Asemahle Nkosi', 'course' => 'Tshivenda', 'progress' => 76],
            ['learner' => 'Asemahle Nkosi', 'course' => 'Xitsonga', 'progress' => 19],
            ['learner' => 'Asemahle Smith', 'course' => 'Computer Applications Technology', 'progress' => 38],
            ['learner' => 'Asemahle Smith', 'course' => 'IsiNdebele', 'progress' => 63],
            ['learner' => 'Asemahle Smith', 'course' => 'IsiZulu', 'progress' => 49],
            ['learner' => 'Asemahle Smith', 'course' => 'Life Orientation', 'progress' => 16],
            ['learner' => 'Asemahle Smith', 'course' => 'Mathematical Literacy', 'progress' => 74],
            ['learner' => 'Blessing Gumede', 'course' => 'IsiXhosa', 'progress' => 27],
            ['learner' => 'Blessing Gumede', 'course' => 'IsiZulu', 'progress' => 3],
            ['learner' => 'Blessing Gumede', 'course' => 'Music', 'progress' => 7],
            ['learner' => 'Blessing Gumede', 'course' => 'Tourism', 'progress' => 80],
            ['learner' => 'Blessing Gumede', 'course' => 'Tshivenda', 'progress' => 35],
            ['learner' => 'Blessing Stadler', 'course' => 'Business Studies', 'progress' => 25],
            ['learner' => 'Blessing Stadler', 'course' => 'Economics', 'progress' => 96],
            ['learner' => 'Blessing Stadler', 'course' => 'English', 'progress' => 36],
            ['learner' => 'Blessing Stadler', 'course' => 'Information Technology', 'progress' => 88],
            ['learner' => 'Blessing Stadler', 'course' => 'Life Orientation', 'progress' => 99],
            ['learner' => 'Blessing Stadler', 'course' => 'Mathematical Literacy', 'progress' => 80],
            ['learner' => 'Blessing Stadler', 'course' => 'Mathematics', 'progress' => 20],
            ['learner' => 'Blessing Stadler', 'course' => 'Sepedi', 'progress' => 3],
            ['learner' => 'Blessing Stadler', 'course' => 'Setswana', 'progress' => 93],
            ['learner' => 'Blessing Stevens', 'course' => 'Afrikaans', 'progress' => 10],
            ['learner' => 'Blessing Stevens', 'course' => 'Dramatic Arts', 'progress' => 65],
            ['learner' => 'Blessing Stevens', 'course' => 'Information Technology', 'progress' => 83],
            ['learner' => 'Blessing Stevens', 'course' => 'Music', 'progress' => 60],
            ['learner' => 'Blessing Stevens', 'course' => 'Siswati', 'progress' => 25],
            ['learner' => 'Blessing Stevens', 'course' => 'Tshivenda', 'progress' => 36],
            ['learner' => 'Cindy Johannisen', 'course' => 'History', 'progress' => 37],
            ['learner' => 'Cindy Johannisen', 'course' => 'Life Orientation', 'progress' => 91],
            ['learner' => 'Cindy Johannisen', 'course' => 'Mathematical Literacy', 'progress' => 52],
            ['learner' => 'Cindy Johannisen', 'course' => 'Music', 'progress' => 77],
            ['learner' => 'Cindy Johannisen', 'course' => 'Setswana', 'progress' => 79],
            ['learner' => 'Cindy Johannisen', 'course' => 'Tshivenda', 'progress' => 85],
            ['learner' => 'Cindy Johannisen', 'course' => 'Xitsonga', 'progress' => 28],
            ['learner' => 'Gift Ndlovu', 'course' => 'Dramatic Arts', 'progress' => 53],
            ['learner' => 'Gift Ndlovu', 'course' => 'Economics', 'progress' => 41],
            ['learner' => 'Gift Ndlovu', 'course' => 'Mathematical Literacy', 'progress' => 53],
            ['learner' => 'Gift Ndlovu', 'course' => 'Music', 'progress' => 8],
            ['learner' => 'Gift Ndlovu', 'course' => 'Sesotho', 'progress' => 43],
            ['learner' => 'Gift Ndlovu', 'course' => 'Tshivenda', 'progress' => 10],
            ['learner' => 'Gift Stevens', 'course' => 'Business Studies', 'progress' => 90],
            ['learner' => 'Gift Stevens', 'course' => 'Dramatic Arts', 'progress' => 55],
            ['learner' => 'Gift Stevens', 'course' => 'Electrical Technology', 'progress' => 26],
            ['learner' => 'Gift Stevens', 'course' => 'Geography', 'progress' => 70],
            ['learner' => 'Gift Stevens', 'course' => 'IsiNdebele', 'progress' => 33],
            ['learner' => 'Gift Stevens', 'course' => 'IsiZulu', 'progress' => 37],
            ['learner' => 'Gift Stevens', 'course' => 'Mathematics', 'progress' => 65],
            ['learner' => 'Gift Stevens', 'course' => 'Siswati', 'progress' => 26],
            ['learner' => 'Gift Stevens', 'course' => 'Xitsonga', 'progress' => 54],
            ['learner' => 'Grace Khumalo', 'course' => 'Life Orientation', 'progress' => 35],
            ['learner' => 'Grace Khumalo', 'course' => 'Sepedi', 'progress' => 26],
            ['learner' => 'Grace Khumalo', 'course' => 'Setswana', 'progress' => 67],
            ['learner' => 'Grace Khumalo', 'course' => 'Tourism', 'progress' => 21],
            ['learner' => 'Grace Ndlovu', 'course' => 'Computer Applications Technology', 'progress' => 82],
            ['learner' => 'Grace Ndlovu', 'course' => 'IsiNdebele', 'progress' => 46],
            ['learner' => 'Grace Ndlovu', 'course' => 'Mathematics', 'progress' => 65],
            ['learner' => 'Grace Ndlovu', 'course' => 'Physical Sciences', 'progress' => 96],
            ['learner' => 'Grace Ndlovu', 'course' => 'Setswana', 'progress' => 36],
            ['learner' => 'Grace Ndlovu', 'course' => 'Siswati', 'progress' => 100],
            ['learner' => 'Grace Ndlovu', 'course' => 'Tshivenda', 'progress' => 34],
            ['learner' => 'Iminathi Stevens', 'course' => 'Hospitality Studies', 'progress' => 23],
            ['learner' => 'Iminathi Stevens', 'course' => 'Information Technology', 'progress' => 62],
            ['learner' => 'Iminathi Stevens', 'course' => 'IsiXhosa', 'progress' => 30],
            ['learner' => 'Iminathi Stevens', 'course' => 'IsiZulu', 'progress' => 37],
            ['learner' => 'Iminathi Stevens', 'course' => 'Physical Sciences', 'progress' => 54],
            ['learner' => 'Iminathi Stevens', 'course' => 'Siswati', 'progress' => 56],
            ['learner' => 'Innocent Ndlovu', 'course' => 'Business Studies', 'progress' => 54],
            ['learner' => 'Innocent Ndlovu', 'course' => 'History', 'progress' => 63],
            ['learner' => 'Innocent Ndlovu', 'course' => 'Information Technology', 'progress' => 49],
            ['learner' => 'Innocent Ndlovu', 'course' => 'IsiXhosa', 'progress' => 21],
            ['learner' => 'Innocent Ndlovu', 'course' => 'Life Orientation', 'progress' => 22],
            ['learner' => 'Innocent Ndlovu', 'course' => 'Sesotho', 'progress' => 44],
            ['learner' => 'Jacob Smith', 'course' => 'Afrikaans', 'progress' => 47],
            ['learner' => 'Jacob Smith', 'course' => 'Geography', 'progress' => 85],
            ['learner' => 'Jacob Smith', 'course' => 'Sepedi', 'progress' => 88],
            ['learner' => 'Jacob Smith', 'course' => 'Siswati', 'progress' => 89],
            ['learner' => 'Jayden Nkosi', 'course' => 'Accounting', 'progress' => 54],
            ['learner' => 'Jayden Nkosi', 'course' => 'Afrikaans', 'progress' => 21],
            ['learner' => 'Jayden Nkosi', 'course' => 'English', 'progress' => 18],
            ['learner' => 'Jayden Nkosi', 'course' => 'History', 'progress' => 78],
            ['learner' => 'Jayden Nkosi', 'course' => 'Hospitality Studies', 'progress' => 87],
            ['learner' => 'Jayden Nkosi', 'course' => 'IsiNdebele', 'progress' => 66],
            ['learner' => 'Jayden Nkosi', 'course' => 'Mathematical Literacy', 'progress' => 83],
            ['learner' => 'Jayden Nkosi', 'course' => 'Setswana', 'progress' => 52],
            ['learner' => 'Jayden Nkosi', 'course' => 'Tourism', 'progress' => 76],
            ['learner' => 'Joanie Stadler', 'course' => 'Business Studies', 'progress' => 97],
            ['learner' => 'Joanie Stadler', 'course' => 'Dramatic Arts', 'progress' => 41],
            ['learner' => 'Joanie Stadler', 'course' => 'Hospitality Studies', 'progress' => 88],
            ['learner' => 'Joanie Stadler', 'course' => 'IsiNdebele', 'progress' => 32],
            ['learner' => 'Joanie Stadler', 'course' => 'IsiXhosa', 'progress' => 48],
            ['learner' => 'Joanie Stadler', 'course' => 'Physical Sciences', 'progress' => 43],
            ['learner' => 'Joanie Stadler', 'course' => 'Sepedi', 'progress' => 76],
            ['learner' => 'Joanie Stadler', 'course' => 'Setswana', 'progress' => 73],
            ['learner' => 'Joanie Stadler', 'course' => 'Tshivenda', 'progress' => 87],
            ['learner' => 'John Smith', 'course' => 'Business Studies', 'progress' => 18],
            ['learner' => 'John Smith', 'course' => 'English', 'progress' => 13],
            ['learner' => 'John Smith', 'course' => 'History', 'progress' => 66],
            ['learner' => 'John Smith', 'course' => 'Life Orientation', 'progress' => 49],
            ['learner' => 'John Smith', 'course' => 'Mathematics', 'progress' => 38],
            ['learner' => 'John Smith', 'course' => 'Tshivenda', 'progress' => 55],
            ['learner' => 'John Smith', 'course' => 'Visual Arts', 'progress' => 63],
            ['learner' => 'Johnathan Botha', 'course' => 'Business Studies', 'progress' => 52],
            ['learner' => 'Johnathan Botha', 'course' => 'IsiNdebele', 'progress' => 44],
            ['learner' => 'Johnathan Botha', 'course' => 'Physical Sciences', 'progress' => 41],
            ['learner' => 'Johnathan Botha', 'course' => 'Visual Arts', 'progress' => 47],
            ['learner' => 'Johnathan Botha', 'course' => 'Xitsonga', 'progress' => 16],
            ['learner' => 'Johnathan Stadler', 'course' => 'Geography', 'progress' => 87],
            ['learner' => 'Johnathan Stadler', 'course' => 'Hospitality Studies', 'progress' => 16],
            ['learner' => 'Johnathan Stadler', 'course' => 'Mathematics', 'progress' => 24],
            ['learner' => 'Johnathan Stadler', 'course' => 'Sepedi', 'progress' => 10],
            ['learner' => 'Johnathan Stadler', 'course' => 'Tourism', 'progress' => 39],
            ['learner' => 'Johnathan Stadler', 'course' => 'Visual Arts', 'progress' => 45],
            ['learner' => 'Johnathan Van Der Merwe', 'course' => 'English', 'progress' => 34],
            ['learner' => 'Johnathan Van Der Merwe', 'course' => 'IsiNdebele', 'progress' => 25],
            ['learner' => 'Johnathan Van Der Merwe', 'course' => 'Tourism', 'progress' => 72],
            ['learner' => 'Junior Botha', 'course' => 'Accounting', 'progress' => 41],
            ['learner' => 'Junior Botha', 'course' => 'Dramatic Arts', 'progress' => 96],
            ['learner' => 'Junior Botha', 'course' => 'English', 'progress' => 18],
            ['learner' => 'Junior Botha', 'course' => 'IsiNdebele', 'progress' => 94],
            ['learner' => 'Junior Botha', 'course' => 'Life Orientation', 'progress' => 47],
            ['learner' => 'Junior Botha', 'course' => 'Physical Sciences', 'progress' => 100],
            ['learner' => 'Junior Botha', 'course' => 'Siswati', 'progress' => 69],
            ['learner' => 'Junior Dlamini', 'course' => 'Accounting', 'progress' => 74],
            ['learner' => 'Junior Dlamini', 'course' => 'Geography', 'progress' => 56],
            ['learner' => 'Junior Dlamini', 'course' => 'Tshivenda', 'progress' => 59],
            ['learner' => 'Junior Johannisen', 'course' => 'English', 'progress' => 35],
            ['learner' => 'Junior Johannisen', 'course' => 'Hospitality Studies', 'progress' => 31],
            ['learner' => 'Junior Johannisen', 'course' => 'Mathematical Literacy', 'progress' => 14],
            ['learner' => 'Junior Johannisen', 'course' => 'Tshivenda', 'progress' => 75],
            ['learner' => 'Junior Mahlangu', 'course' => 'English', 'progress' => 55],
            ['learner' => 'Junior Mahlangu', 'course' => 'Life Orientation', 'progress' => 64],
            ['learner' => 'Junior Mahlangu', 'course' => 'Life Sciences', 'progress' => 20],
            ['learner' => 'Junior Mahlangu', 'course' => 'Setswana', 'progress' => 44],
            ['learner' => 'Junior Mahlangu', 'course' => 'Siswati', 'progress' => 57],
            ['learner' => 'Jurie Botha', 'course' => 'Computer Applications Technology', 'progress' => 74],
            ['learner' => 'Jurie Botha', 'course' => 'Information Technology', 'progress' => 53],
            ['learner' => 'Jurie Botha', 'course' => 'Life Orientation', 'progress' => 6],
            ['learner' => 'Jurie Botha', 'course' => 'Xitsonga', 'progress' => 49],
            ['learner' => 'Jurie Gumede', 'course' => 'Afrikaans', 'progress' => 72],
            ['learner' => 'Jurie Gumede', 'course' => 'Hospitality Studies', 'progress' => 13],
            ['learner' => 'Jurie Gumede', 'course' => 'Life Sciences', 'progress' => 62],
            ['learner' => 'Jurie Gumede', 'course' => 'Mathematical Literacy', 'progress' => 98],
            ['learner' => 'Jurie Gumede', 'course' => 'Music', 'progress' => 94],
            ['learner' => 'Jurie Gumede', 'course' => 'Physical Sciences', 'progress' => 65],
            ['learner' => 'Jurie Gumede', 'course' => 'Sepedi', 'progress' => 50],
            ['learner' => 'Jurie Gumede', 'course' => 'Sesotho', 'progress' => 100],
            ['learner' => 'Jurie Gumede', 'course' => 'Setswana', 'progress' => 20],
            ['learner' => 'Lethabo Botha', 'course' => 'Afrikaans', 'progress' => 98],
            ['learner' => 'Lethabo Botha', 'course' => 'Business Studies', 'progress' => 21],
            ['learner' => 'Lethabo Botha', 'course' => 'Economics', 'progress' => 16],
            ['learner' => 'Lethabo Botha', 'course' => 'IsiZulu', 'progress' => 51],
            ['learner' => 'Lethabo Botha', 'course' => 'Life Sciences', 'progress' => 30],
            ['learner' => 'Lethabo Botha', 'course' => 'Music', 'progress' => 25],
            ['learner' => 'Lethabo Dlamini', 'course' => 'Afrikaans', 'progress' => 46],
            ['learner' => 'Lethabo Dlamini', 'course' => 'Hospitality Studies', 'progress' => 61],
            ['learner' => 'Lethabo Dlamini', 'course' => 'IsiZulu', 'progress' => 41],
            ['learner' => 'Lethabo Dlamini', 'course' => 'Life Orientation', 'progress' => 14],
            ['learner' => 'Lethabo Dlamini', 'course' => 'Siswati', 'progress' => 93],
            ['learner' => 'Lethabo Mahlangu', 'course' => 'Afrikaans', 'progress' => 24],
            ['learner' => 'Lethabo Mahlangu', 'course' => 'Economics', 'progress' => 70],
            ['learner' => 'Lethabo Mahlangu', 'course' => 'Geography', 'progress' => 39],
            ['learner' => 'Lethabo Mahlangu', 'course' => 'IsiNdebele', 'progress' => 5],
            ['learner' => 'Lethabo Mahlangu', 'course' => 'Sepedi', 'progress' => 74],
            ['learner' => 'Lethabo Mahlangu', 'course' => 'Sesotho', 'progress' => 78],
            ['learner' => 'Lethabo Nkosi', 'course' => 'Geography', 'progress' => 84],
            ['learner' => 'Lethabo Nkosi', 'course' => 'Hospitality Studies', 'progress' => 4],
            ['learner' => 'Lethabo Nkosi', 'course' => 'Life Orientation', 'progress' => 93],
            ['learner' => 'Lethabo Nkosi', 'course' => 'Sepedi', 'progress' => 79],
            ['learner' => 'Lethabo Sithole', 'course' => 'Business Studies', 'progress' => 99],
            ['learner' => 'Lethabo Sithole', 'course' => 'Life Sciences', 'progress' => 97],
            ['learner' => 'Lethabo Sithole', 'course' => 'Physical Sciences', 'progress' => 38],
            ['learner' => 'Lethabo Sithole', 'course' => 'Sesotho', 'progress' => 8],
            ['learner' => 'Lethabo Sithole', 'course' => 'Siswati', 'progress' => 45],
            ['learner' => 'Lethokuhle Botha', 'course' => 'Afrikaans', 'progress' => 57],
            ['learner' => 'Lethokuhle Botha', 'course' => 'English', 'progress' => 28],
            ['learner' => 'Lethokuhle Botha', 'course' => 'Geography', 'progress' => 58],
            ['learner' => 'Lethokuhle Botha', 'course' => 'Life Orientation', 'progress' => 88],
            ['learner' => 'Lethokuhle Botha', 'course' => 'Xitsonga', 'progress' => 91],
            ['learner' => 'Lethokuhle Geldenhuys', 'course' => 'Accounting', 'progress' => 27],
            ['learner' => 'Lethokuhle Geldenhuys', 'course' => 'English', 'progress' => 62],
            ['learner' => 'Lethokuhle Geldenhuys', 'course' => 'Information Technology', 'progress' => 10],
            ['learner' => 'Lethokuhle Geldenhuys', 'course' => 'Physical Sciences', 'progress' => 72],
            ['learner' => 'Lethokuhle Mkhize', 'course' => 'Electrical Technology', 'progress' => 18],
            ['learner' => 'Lethokuhle Mkhize', 'course' => 'Music', 'progress' => 75],
            ['learner' => 'Lethokuhle Mkhize', 'course' => 'Physical Sciences', 'progress' => 48],
            ['learner' => 'Lethokuhle Mkhize', 'course' => 'Sesotho', 'progress' => 61],
            ['learner' => 'Lethokuhle Stevens', 'course' => 'Accounting', 'progress' => 32],
            ['learner' => 'Lethokuhle Stevens', 'course' => 'Dramatic Arts', 'progress' => 59],
            ['learner' => 'Lethokuhle Stevens', 'course' => 'Economics', 'progress' => 80],
            ['learner' => 'Lethokuhle Stevens', 'course' => 'Setswana', 'progress' => 77],
            ['learner' => 'Lethokuhle Stevens', 'course' => 'Visual Arts', 'progress' => 63],
            ['learner' => 'Lisakhanya Du Toit', 'course' => 'Electrical Technology', 'progress' => 22],
            ['learner' => 'Lisakhanya Du Toit', 'course' => 'Geography', 'progress' => 51],
            ['learner' => 'Lisakhanya Du Toit', 'course' => 'Setswana', 'progress' => 60],
            ['learner' => 'Lisakhanya Du Toit', 'course' => 'Siswati', 'progress' => 96],
            ['learner' => 'Lisakhanya Mkhize', 'course' => 'Information Technology', 'progress' => 98],
            ['learner' => 'Lisakhanya Mkhize', 'course' => 'Mathematical Literacy', 'progress' => 77],
            ['learner' => 'Lisakhanya Mkhize', 'course' => 'Visual Arts', 'progress' => 54],
            ['learner' => 'Lisakhanya Mkhize', 'course' => 'Xitsonga', 'progress' => 28],
            ['learner' => 'Lubanz Ngcobo', 'course' => 'Accounting', 'progress' => 53],
            ['learner' => 'Lubanz Ngcobo', 'course' => 'Economics', 'progress' => 87],
            ['learner' => 'Lubanz Ngcobo', 'course' => 'Electrical Technology', 'progress' => 15],
            ['learner' => 'Lubanz Ngcobo', 'course' => 'English', 'progress' => 81],
            ['learner' => 'Lubanz Ngcobo', 'course' => 'History', 'progress' => 50],
            ['learner' => 'Lubanz Ngcobo', 'course' => 'IsiNdebele', 'progress' => 99],
            ['learner' => 'Lubanz Ngcobo', 'course' => 'Tourism', 'progress' => 69],
            ['learner' => 'Lubanz Ngcobo', 'course' => 'Tshivenda', 'progress' => 47],
            ['learner' => 'Lubanz Van Der Merwe', 'course' => 'IsiZulu', 'progress' => 85],
            ['learner' => 'Lubanz Van Der Merwe', 'course' => 'Life Sciences', 'progress' => 37],
            ['learner' => 'Lubanz Van Der Merwe', 'course' => 'Mathematical Literacy', 'progress' => 9],
            ['learner' => 'Lubanz Van Der Merwe', 'course' => 'Music', 'progress' => 88],
            ['learner' => 'Lubanz Van Der Merwe', 'course' => 'Physical Sciences', 'progress' => 3],
            ['learner' => 'Lubanz Van Der Merwe', 'course' => 'Sesotho', 'progress' => 30],
            ['learner' => 'Lubanz Van Der Merwe', 'course' => 'Setswana', 'progress' => 39],
            ['learner' => 'Lubanz Van Der Merwe', 'course' => 'Visual Arts', 'progress' => 49],
            ['learner' => 'Lubanzi Gumede', 'course' => 'Accounting', 'progress' => 90],
            ['learner' => 'Lubanzi Gumede', 'course' => 'Business Studies', 'progress' => 98],
            ['learner' => 'Lubanzi Gumede', 'course' => 'Mathematical Literacy', 'progress' => 61],
            ['learner' => 'Lubanzi Gumede', 'course' => 'Tourism', 'progress' => 98],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'Business Studies', 'progress' => 11],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'Computer Applications Technology', 'progress' => 79],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'Dramatic Arts', 'progress' => 34],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'IsiZulu', 'progress' => 54],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'Mathematical Literacy', 'progress' => 51],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'Sepedi', 'progress' => 65],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'Sesotho', 'progress' => 21],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'Setswana', 'progress' => 55],
            ['learner' => 'Lubanzi Mahlangu', 'course' => 'Visual Arts', 'progress' => 10],
            ['learner' => 'Lwandle Sithole', 'course' => 'Dramatic Arts', 'progress' => 62],
            ['learner' => 'Lwandle Sithole', 'course' => 'Economics', 'progress' => 29],
            ['learner' => 'Lwandle Sithole', 'course' => 'Electrical Technology', 'progress' => 84],
            ['learner' => 'Lwandle Sithole', 'course' => 'IsiNdebele', 'progress' => 24],
            ['learner' => 'Lwandle Sithole', 'course' => 'Mathematics', 'progress' => 64],
            ['learner' => 'Lwandle Sithole', 'course' => 'Sepedi', 'progress' => 73],
            ['learner' => 'Lwandle Sithole', 'course' => 'Setswana', 'progress' => 40],
            ['learner' => 'Lwandle Sithole', 'course' => 'Tshivenda', 'progress' => 3],
            ['learner' => 'Lwandle Smith', 'course' => 'Accounting', 'progress' => 29],
            ['learner' => 'Lwandle Smith', 'course' => 'Computer Applications Technology', 'progress' => 2],
            ['learner' => 'Lwandle Smith', 'course' => 'Sepedi', 'progress' => 62],
            ['learner' => 'Lwandle Smith', 'course' => 'Setswana', 'progress' => 8],
            ['learner' => 'Lwandle Smith', 'course' => 'Tourism', 'progress' => 25],
            ['learner' => 'Melokuhle Botha', 'course' => 'Computer Applications Technology', 'progress' => 18],
            ['learner' => 'Melokuhle Botha', 'course' => 'Economics', 'progress' => 43],
            ['learner' => 'Melokuhle Botha', 'course' => 'Life Orientation', 'progress' => 87],
            ['learner' => 'Melokuhle Botha', 'course' => 'Tshivenda', 'progress' => 38],
            ['learner' => 'Melokuhle Botha', 'course' => 'Xitsonga', 'progress' => 67],
            ['learner' => 'Melokuhle Khumalo', 'course' => 'Life Sciences', 'progress' => 8],
            ['learner' => 'Melokuhle Khumalo', 'course' => 'Mathematical Literacy', 'progress' => 74],
            ['learner' => 'Melokuhle Khumalo', 'course' => 'Tourism', 'progress' => 14],
            ['learner' => 'Melokuhle Mahlangu', 'course' => 'Accounting', 'progress' => 75],
            ['learner' => 'Melokuhle Mahlangu', 'course' => 'Afrikaans', 'progress' => 18],
            ['learner' => 'Melokuhle Mahlangu', 'course' => 'Geography', 'progress' => 64],
            ['learner' => 'Melokuhle Mahlangu', 'course' => 'History', 'progress' => 93],
            ['learner' => 'Melokuhle Mahlangu', 'course' => 'Life Orientation', 'progress' => 63],
            ['learner' => 'Melokuhle Mahlangu', 'course' => 'Siswati', 'progress' => 28],
            ['learner' => 'Melokuhle Mahlangu', 'course' => 'Tshivenda', 'progress' => 60],
            ['learner' => 'Melokuhle Smith', 'course' => 'Afrikaans', 'progress' => 88],
            ['learner' => 'Melokuhle Smith', 'course' => 'History', 'progress' => 74],
            ['learner' => 'Melokuhle Smith', 'course' => 'IsiZulu', 'progress' => 8],
            ['learner' => 'Melokuhle Smith', 'course' => 'Life Orientation', 'progress' => 13],
            ['learner' => 'Melokuhle Smith', 'course' => 'Life Sciences', 'progress' => 2],
            ['learner' => 'Melokuhle Smith', 'course' => 'Music', 'progress' => 93],
            ['learner' => 'Melokuhle Van Der Merwe', 'course' => 'History', 'progress' => 84],
            ['learner' => 'Melokuhle Van Der Merwe', 'course' => 'IsiNdebele', 'progress' => 3],
            ['learner' => 'Melokuhle Van Der Merwe', 'course' => 'IsiZulu', 'progress' => 28],
            ['learner' => 'Melokuhle Van Der Merwe', 'course' => 'Physical Sciences', 'progress' => 6],
            ['learner' => 'Melokuhle Van Der Merwe', 'course' => 'Tourism', 'progress' => 83],
            ['learner' => 'Melokuhle Van Der Merwe', 'course' => 'Xitsonga', 'progress' => 91],
            ['learner' => 'Nora Ndlovu', 'course' => 'Life Orientation', 'progress' => 36],
            ['learner' => 'Nora Ndlovu', 'course' => 'Mathematics', 'progress' => 90],
            ['learner' => 'Nora Ndlovu', 'course' => 'Physical Sciences', 'progress' => 90],
            ['learner' => 'Ofentse Sithole', 'course' => 'Business Studies', 'progress' => 92],
            ['learner' => 'Ofentse Sithole', 'course' => 'Geography', 'progress' => 74],
            ['learner' => 'Ofentse Sithole', 'course' => 'History', 'progress' => 47],
            ['learner' => 'Ofentse Sithole', 'course' => 'Sepedi', 'progress' => 97],
            ['learner' => 'Ofentse Sithole', 'course' => 'Tourism', 'progress' => 68],
            ['learner' => 'Ofentse Van Der Merwe', 'course' => 'English', 'progress' => 38],
            ['learner' => 'Ofentse Van Der Merwe', 'course' => 'Geography', 'progress' => 35],
            ['learner' => 'Ofentse Van Der Merwe', 'course' => 'IsiZulu', 'progress' => 96],
            ['learner' => 'Ofentse Van Der Merwe', 'course' => 'Sesotho', 'progress' => 48],
            ['learner' => 'Ofentse Van Der Merwe', 'course' => 'Siswati', 'progress' => 42],
            ['learner' => 'Ofentse Van Der Merwe', 'course' => 'Xitsonga', 'progress' => 15],
            ['learner' => 'Prince Nkosi', 'course' => 'Electrical Technology', 'progress' => 21],
            ['learner' => 'Prince Nkosi', 'course' => 'Hospitality Studies', 'progress' => 39],
            ['learner' => 'Prince Nkosi', 'course' => 'Information Technology', 'progress' => 35],
            ['learner' => 'Prince Nkosi', 'course' => 'IsiNdebele', 'progress' => 78],
            ['learner' => 'Prince Nkosi', 'course' => 'Life Orientation', 'progress' => 37],
            ['learner' => 'Prince Nkosi', 'course' => 'Music', 'progress' => 19],
            ['learner' => 'Prince Nkosi', 'course' => 'Tshivenda', 'progress' => 34],
            ['learner' => 'Princess Nkosi', 'course' => 'History', 'progress' => 86],
            ['learner' => 'Princess Nkosi', 'course' => 'IsiXhosa', 'progress' => 20],
            ['learner' => 'Princess Nkosi', 'course' => 'Life Orientation', 'progress' => 49],
            ['learner' => 'Princess Nkosi', 'course' => 'Life Sciences', 'progress' => 99],
            ['learner' => 'Princess Nkosi', 'course' => 'Siswati', 'progress' => 77],
            ['learner' => 'Siphosethu Ndlovu', 'course' => 'IsiNdebele', 'progress' => 11],
            ['learner' => 'Siphosethu Ndlovu', 'course' => 'Life Orientation', 'progress' => 94],
            ['learner' => 'Siphosethu Ndlovu', 'course' => 'Physical Sciences', 'progress' => 98],
            ['learner' => 'Siphosethu Ndlovu', 'course' => 'Sesotho', 'progress' => 43],
            ['learner' => 'Siphosethu Ndlovu', 'course' => 'Siswati', 'progress' => 39],
            ['learner' => 'Siphosethu Ndlovu', 'course' => 'Tourism', 'progress' => 25],
        ];

        foreach ($enrolments as $enrolment) {
            $learnerId = $learners[$enrolment['learner']] ?? null;
            $courseId = $courses[$enrolment['course']] ?? null;

            if ($learnerId && $courseId) {
                Enrolment::query()->create([
                    'learner_id' => $learnerId,
                    'course_id' => $courseId,
                    'progress' => $enrolment['progress'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
